### ISSUE TITLE
The generated prompts are all duplicates

### ISSUE THREAD

**Issue by tropical-algae** [VITA-Group/DP-OPT#2]
When we tested this code on the SST2 dataset, we noticed that the multiple prompts generated by the model were exactly the same, which was somewhat unexpected. 

We set up the environment on Ubuntu 22.04 following the recommendations in the README file, using a single A100 GPU to conduct the experiments. The CUDA version and other relevant information are as follows: NVIDIA-SMI 545.29.06, Driver Version: 545.29.06, CUDA Version: 12.3.

Could you kindly advise us on how we might address this issue? Below are our training parameters and some sample model outputs:

```
python train_opt.py --ape_mode=iid_ibwd --ensemble_gen=True --gen_temp=1.1 --num_prompt=40 --max_new_tokens=50 \
--data=sst2 --holdout_ratio=0.01 \
--target_eps=8. --dp_eps=1.8 --dp_delta=5e-7 --tokenwise_gen=True
```

<img width="591" alt="20240714150848" src="https://github.com/user-attachments/assets/21798730-92d9-4616-bb02-6bdcb8212ba6">

**Comment by jyhong836** [comment]
Hi.
Is it always outputting the same? In our experiment, the program did output the same in 90% cases. Only a few prompts will be different, that works better.

**Comment by tropical-algae** [comment]
> Hi. Is it always outputting the same? In our experiment, the program did output the same in 90% cases. Only a few prompts will be different, that works better.

There are indeed some different prompts, and we mistakenly thought this was an abnormal phenomenon. Thank you for your response.
