### ISSUE TITLE
Thank you for the code you provided. I have a question about running this code

### ISSUE THREAD

**Issue by qilee-work** [VITA-Group/DP-OPT#3]
![errpr](https://github.com/user-attachments/assets/a5f4e391-ac11-4055-92ee-6efb36116db8)

When I debug this line,  the result of (stopping_criteria(cur_input_ids, None)) is a list, and all values is True. Like [True,True,....] So how can I fix this code?  return torch.sum()? 
![error2](https://github.com/user-attachments/assets/d15f6667-2ba2-4fea-a691-1eafed500529)

**Comment by jyhong836** [comment]
What is the version of your `transformers`? Could you try to use `transformers==4.28.1`?
